
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author njood
 */
public class DeFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeFrame
     */
    public DeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jLabel3 = new javax.swing.JLabel();
        key = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        plaintext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ciphertext = new javax.swing.JTextField();
        decrypt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        enframe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setText("Key:");

        jLabel2.setText("Plaintext:");

        plaintext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plaintextActionPerformed(evt);
            }
        });

        jLabel1.setText("Ciphertext:");

        ciphertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciphertextActionPerformed(evt);
            }
        });

        decrypt.setText("Decrypt");
        decrypt.setDoubleBuffered(true);
        decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptActionPerformed(evt);
            }
        });

        jMenu1.setText("Browse");

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenu1.add(home);

        enframe.setText("Encrypt");
        enframe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enframeActionPerformed(evt);
            }
        });
        jMenu1.add(enframe);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(decrypt, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ciphertext)
                                    .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(plaintext, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ciphertext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(decrypt)
                        .addGap(18, 18, 18)
                        .addComponent(plaintext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plaintextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plaintextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plaintextActionPerformed

    private void ciphertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciphertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciphertextActionPerformed

    private void decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptActionPerformed
        // TODO add your handling code here:
       
      
    
       String text = ciphertext.getText().toUpperCase();
       String k = key.getText().toUpperCase();
       String[] cut = text.split(" ");
       
        if(k.length() > text.length()){
       JOptionPane.showMessageDialog(null, "Key shouldn’t be longer than text length");
       plaintext.setText("");
       key.setText("");
       ciphertext.setText("");
       return;}

       text = "";
       for(int i=0; i<cut.length; i++)
           text+=cut[i];


        if (text.equals("") || k.equals("")){
        JOptionPane.showMessageDialog(null, "Empty text or key! . \n Please re enter both text and key.");
        return;}

       if(validate(text)&&validate(k))
           plaintext.setText(decrypt(text,k));

       else {
           JOptionPane.showMessageDialog(null, "The text or key you entered is not valid. \n Please use characters from A-Z or a-z.");
           ciphertext.setText("");
            key.setText("");
            plaintext.setText("");
       }        
        
    }
    //GEN-LAST:event_decryptActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        GUI f = new GUI();
        f.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void enframeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enframeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EnFrame e = new EnFrame();
        e.setVisible(true);
    }//GEN-LAST:event_enframeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeFrame().setVisible(true);
            }
        });
    }
    
    public boolean validate(String str){
        str = str.trim().toUpperCase();
        for(int i=0; i<str.length(); i++){
          if(!Character.isLetter(str.charAt(i)))
              return false;
        }
     return true;
    }
    
    public String decrypt(String text, String key){
        
         //Create table, scrollpane, and jframe. 
        JTable t = new JTable(6, text.length()); 
        t.setDefaultEditor(Object.class, null);
        t.setBounds(30,40,200,300);
        t.setDragEnabled(false);
        t.setTableHeader(null);
        t.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        JScrollPane sp = new JScrollPane(t,JScrollPane.VERTICAL_SCROLLBAR_NEVER, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED); 
        JFrame tableframe = new JFrame();
        
        //Add pane to frame, but make sure its empty first  
        if(sp.getParent()!=null)
            tableframe.removeAll(); 
        tableframe.add(sp);
        tableframe.setSize(300,400); 
        tableframe.setVisible(true);
        
         // To populate first two rows (Ciphertext characters and their values)
        int row = 0, val;
        for(int i=0; i<text.length(); i++){
            t.setValueAt(text.charAt(i), row++, i);
            val = text.charAt(i)-65;
            t.setValueAt(val, row, i);
            row = 0;
        }
        
        // To populate second two rows (Key characters and their values)
        int ki = 0;
        row = 2;
        for(int i=0; i<text.length(); i++){
            t.setValueAt(key.charAt(ki), row++, i);
            val = key.charAt(ki)-65;
            t.setValueAt(val, row, i);
            row = 2;
            ki++;    
            if(ki == key.length())
                ki = 0;
        }
              
        // To populate remaining rows (Plaintext values and their corresponding characters)
        String plaintext = "";
        row = 4;
        int pe;
        String pt;
        for(int i=0; i<text.length(); i++){
            pt = "";
            System.out.println(t.getValueAt(1,i).toString());
            int n1 = Integer.parseInt((t.getValueAt(1, i).toString()));
            int n2 = Integer.parseInt(t.getValueAt(3, i).toString());
            pe = n1-n2;
            if (pe < 0)
                pe+=26;
            else
                pe%=26;
            t.setValueAt(pe, row++, i);
            pt += (char)(pe+65);
            t.setValueAt(pt, row, i);
            row = 4;
            plaintext+=pt;
        }
        
        
        
        
        return plaintext;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ciphertext;
    private javax.swing.JButton decrypt;
    private javax.swing.JMenuItem enframe;
    private javax.swing.JMenuItem home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JTextField key;
    private javax.swing.JTextField plaintext;
    // End of variables declaration//GEN-END:variables
}
